<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\City;
class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();
        $cities = array(
            array('name' => 'Abnūb'),
            array('name' => 'Abu Simbel'),
            array('name' => 'Abū Qurqāş'),
            array('name' => 'Abū Tīj'),
            array('name' => 'Abū al Maţāmīr'),
            array('name' => 'Ad Dilinjāt'),
            array('name' => 'Ain Sukhna'),
            array('name' => 'Ajā'),
            array('name' => 'Akhmīm'),
            array('name' => 'Al Badārī'),
            array('name' => 'Al Balyanā'),
            array('name' => 'Al Bawīţī'),
            array('name' => 'Al Bājūr'),
            array('name' => 'Al Fashn'),
            array('name' => 'Al Fayyūm'),
            array('name' => 'Al Jammālīyah'),
            array('name' => 'Al Khānkah'),
            array('name' => 'Al Khārijah'),
            array('name' => 'Al Manshāh'),
            array('name' => 'Al Manzalah'),
            array('name' => 'Al Manşūrah'),
            array('name' => 'Al Maţarīyah'),
            array('name' => 'Al Maḩallah al Kubrá'),
            array('name' => 'Al Minyā'),
            array('name' => 'Al Qanāţir al Khayrīyah'),
            array('name' => 'Al Quşayr'),
            array('name' => 'Al Qūşīyah'),
            array('name' => 'Al Wāsiţah'),
            array('name' => 'Al Ḩawāmidīyah'),
            array('name' => 'Al Ḩāmūl'),
            array('name' => 'Al ‘Alamayn'),
            array('name' => 'Al ‘Ayyāţ'),
            array('name' => 'Alexandria'),
            array('name' => 'Arish'),
            array('name' => 'Ash Shuhadā’'),
            array('name' => 'Ashmūn'),
            array('name' => 'Aswan'),
            array('name' => 'Asyūţ'),
            array('name' => 'Awsīm'),
            array('name' => 'Az Zarqā'),
            array('name' => 'Aş Şaff'),
            array('name' => 'Banhā'),
            array('name' => 'Banī Mazār'),
            array('name' => 'Banī Suwayf'),
            array('name' => 'Basyūn'),
            array('name' => 'Bilqās'),
            array('name' => 'Būsh'),
            array('name' => 'Cairo'),
            array('name' => 'Dahab'),
            array('name' => 'Damanhūr'),
            array('name' => 'Damietta'),
            array('name' => 'Dayr Mawās'),
            array('name' => 'Dayrūţ'),
            array('name' => 'Dikirnis'),
            array('name' => 'Dishnā'),
            array('name' => 'Disūq'),
            array('name' => 'El Gouna'),
            array('name' => 'El-Tor'),
            array('name' => 'Farshūţ'),
            array('name' => 'Fuwwah'),
            array('name' => 'Fāraskūr'),
            array('name' => 'Giza'),
            array('name' => 'Hurghada'),
            array('name' => 'Ibshawāy'),
            array('name' => 'Idfū'),
            array('name' => 'Idkū'),
            array('name' => 'Ismailia'),
            array('name' => 'Isnā'),
            array('name' => 'Iţsā'),
            array('name' => 'Jirjā'),
            array('name' => 'Juhaynah'),
            array('name' => 'Kafr ad Dawwār'),
            array('name' => 'Kafr ash Shaykh'),
            array('name' => 'Kafr az Zayyāt'),
            array('name' => 'Kawm Umbū'),
            array('name' => 'Kawm Ḩamādah'),
            array('name' => 'Kousa'),
            array('name' => 'Luxor'),
            array('name' => 'Madīnat Sittah Uktūbar'),
            array('name' => 'Makadi Bay'),
            array('name' => 'Mallawī'),
            array('name' => 'Manfalūţ'),
            array('name' => 'Markaz Disūq'),
            array('name' => 'Markaz Jirjā'),
            array('name' => 'Markaz Sūhāj'),
            array('name' => 'Markaz al Uqşur'),
            array('name' => 'Marsa Alam'),
            array('name' => 'Maţāy'),
            array('name' => 'Mersa Matruh'),
            array('name' => 'Minyat an Naşr'),
            array('name' => 'Munshāt ‘Alī Āghā'),
            array('name' => 'Munūf'),
            array('name' => 'Naja\' Ḥammādī'),
            array('name' => 'Nuwaybi‘a'),
            array('name' => 'Port Said'),
            array('name' => 'Qalyūb'),
            array('name' => 'Qaşr al Farāfirah'),
            array('name' => 'Qinā'),
            array('name' => 'Quwaysinā'),
            array('name' => 'Quţūr'),
            array('name' => 'Ras Gharib'),
            array('name' => 'Rosetta'),
            array('name' => 'Safaga'),
            array('name' => 'Saint Catherine'),
            array('name' => 'Samannūd'),
            array('name' => 'Samālūţ'),
            array('name' => 'Sharm el-Sheikh'),
            array('name' => 'Shibīn al Kawm'),
            array('name' => 'Shibīn al Qanāṭir'),
            array('name' => 'Shirbīn'),
            array('name' => 'Siwa Oasis'),
            array('name' => 'Sohag'),
            array('name' => 'Suez'),
            array('name' => 'Sumusţā as Sulţānī'),
            array('name' => 'Sīdī Sālim'),
            array('name' => 'Talā'),
            array('name' => 'Tanda'),
            array('name' => 'Toukh'),
            array('name' => 'Zefta'),
            array('name' => 'Ţahţā'),
            array('name' => 'Ţalkhā'),
            array('name' => 'Ţāmiyah'),
            array('name' => 'Ḩawsh ‘Īsá'),
            array('name' => '‘Izbat al Burj'),
            array('name' => '10th of Ramadan'),
            array('name' => 'Markaz Abū Ḩammād'),
            array('name' => 'Awlad Saqr'),
            array('name' => 'Bilbeis'),
            array('name' => 'Diyarb Negm'),
            array('name' => 'El Husseiniya'),
            array('name' => 'Al Qurein'),
            array('name' => 'Faqous'),
            array('name' => 'Hihya'),
            array('name' => 'Kafr Saqr'),
            array('name' => 'Mashtoul El Souk'),
            array('name' => 'Minya El Qamh'),
            array('name' => 'New Salhia'),
            array('name' => 'Zagazig'),
            array('name' => 'Badr'),
            array('name' => 'Bulaq'),
            array('name' => 'El Mataria'),
            array('name' => 'Fustat'),
            array('name' => 'Hadayek El Kobba'),
            array('name' => 'Heliopolis'),
            array('name' => 'Helwan'),
            array('name' => 'Maadi'),
            array('name' => 'Musturud'),
            array('name' => 'New Administrative Capital of Egypt'),
            array('name' => 'Shubra'),
            array('name' => 'Tura'),
            array('name' => 'Abu Qir'),
            array('name' => 'Agami'),
            array('name' => 'Ar-Raml'),
            array('name' => 'Borg El Arab'),
            array('name' => 'Montaza'),
            array('name' => 'New Borg El Arab'),
            array('name' => 'Sidi Bishr')
          );
          
          foreach ($cities as $city) {
              City::create(['name'=>$city['name'],'country_id'=>1]);
          }
}

    }

